apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flux
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: flux
    spec:
      containers:
      - name: fluxd
        image: weaveworks/fluxd:test
        args:
        - --fluxsvc-address=ws://localhost:3030
      - name: fluxsvc
        image: weaveworks/fluxsvc:test
        args:
        - --database-source=file://fluxy.db
